Testdjango/Testdjango/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('api/', include('rest_proveedor.urls')),
]

Testdjango/core/urls.py
from django.urls import path
from core.views import home,contacto,seccion_gatos,seccion_perros,agregar_proveedores, proveedores,eliminar_proveedores,modificar_proveedores

app_name='core'

urlpatterns = [
    path('', home, name="home"),
    path('agregar/', agregar_proveedores , name="agregar"),
    path('proveedores/', proveedores , name="proveedores"),
    path('eliminar/<id>', eliminar_proveedores , name="eliminar"),
    path('modificar/<id>', modificar_proveedores , name="modificar"),   
    path('contacto/', contacto, name="contacto"),
    path('home/', home, name="home"),
    path('gatos/', seccion_gatos, name="gatos"),
    path('perros/', seccion_perros, name="perros"),
   
    
]

Testdjango/rest_proveedor/urls.py
from django.urls import path 
from rest_proveedor.views import lista_proveedores, agregar_proveedor, detalle_proveedor
from rest_proveedor.viewsLogin import login

urlpatterns = [
    path('lista_proveedores', lista_proveedores, name='lista_proveedores'),
    path('agregar_proveedor', agregar_proveedor, name='agregar_proveedor' ),
    path('detalle_proveedor/<id>', detalle_proveedor, name='detalle_proveedor'),
    path('login', login, name='login'),
]

Testdjango/core/models.py
from django.db import models

# Create your models here.

class Servicio (models.Model):
    id_servicio= models.IntegerField(primary_key=True, verbose_name='ID de servicio')
    nombre_servicio = models.CharField(max_length=50, verbose_name='Nombre del Servicio')

    def __str__(self):
        return self.nombre_servicio

class Proveedor(models.Model):
    rut=models.CharField(max_length=20)
    razon_social=models.CharField(max_length=50)
    descripcion=models.CharField(max_length=100)
    telefono=models.CharField(max_length=15)
    email=models.CharField(max_length=50)
    servicio=models.ForeignKey(Servicio, on_delete=models.CASCADE)
  
    def str(self):
        return self.rut

Testdjango/rest_proveedor/models.py
from django.db import models

# Create your models here.

Testdjango/core/forms.py
from django import forms
from .models import Proveedor


class ProveedorForm(forms.ModelForm):

    class Meta:
        model=Proveedor
        fields='__all__'

Testdjango/core/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import ProveedorForm
from .models import Proveedor
from django.contrib import messages

# Create your views here.

def home(request):

    return render(request, 'core/home.html')

def contacto(request):

    return render(request, 'core/contacto.html')

def seccion_gatos(request):

    return render(request, 'core/seccion-gatos.html')

def seccion_perros(request):

    return render(request, 'core/seccion-perros.html')


def agregar_proveedores(request):

    data = {
        'form': ProveedorForm()
    }
    if request.method == 'POST':
        formulario = ProveedorForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, 'Proveedor agregado exitosamente')
            return redirect(to='core:proveedores')
        data["form"] = formulario
    
    return render(request, 'core/agregar_proveedores.html',data)

def proveedores(request):

    proveedores = Proveedor.objects.all()
    data = {
        'proveedores': proveedores
    }
    
    return render(request, 'core/proveedores.html', data)


def eliminar_proveedores(request,id):

    proveedores = get_object_or_404(Proveedor, id=id)
    proveedores.delete()
    messages.success(request, 'Proveedor eliminado exitosamente')
    return redirect(to='core:proveedores')   

def modificar_proveedores(request,id):

    proveedores = get_object_or_404(Proveedor, id=id)
    data = {
        'form': ProveedorForm(instance=proveedores)
    }
    if request.method == 'POST':
        formulario = ProveedorForm(data=request.POST, instance=proveedores)
        if formulario.is_valid():             
            formulario.save()       
            messages.success(request, 'Proveedor modificado exitosamente')
            return redirect(to='core:proveedores')                 
        data["form"] = formulario
    return render(request, 'core/modificar_proveedor.html', data)   

Testdjango/rest_proveedor/views.py
from django.shortcuts import render
from rest_framework import status
from rest_framework.decorators import api_view,permission_classes
from rest_framework.response import Response 
from rest_framework.parsers import JSONParser
from django.views.decorators.csrf import csrf_exempt
from core.models import Proveedor 
from .serializers import ProveedorSerializer

from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
@csrf_exempt
@api_view(['GET'])
@permission_classes ((IsAuthenticated,))
def lista_proveedores(request):
    """
    Lista todos los Proveedores
    """
    proveedor = Proveedor.objects.all()
    serializer = ProveedorSerializer(proveedor, many=True)
    return Response(serializer.data)

@csrf_exempt
@api_view(['POST'])
@permission_classes ((IsAuthenticated,))
def agregar_proveedor(request):
    if request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = ProveedorSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        
@api_view(['GET','PUT','DELETE'])
@permission_classes ((IsAuthenticated,))
def detalle_proveedor(request,id):
    """
    Get, update, o delete de un proveedor en particular
    """
    try:
        proveedor = Proveedor.objects.get(rut=id)
    except Proveedor.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == 'GET':
        serializer = ProveedorSerializer(proveedor)
        return Response(serializer.data)
    
    if request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = ProveedorSerializer(proveedor,data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        proveedor.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

# Create your views here.

Testdjango/core/templates/core/agregar_proveedores.html
<!DOCTYPE html>
<html lang="es">

<head>
    {% load static %}
    <title>ONG Ayuda a un peludo</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/estilo.css">
    <link href="{% static 'css/estilo_tabla.css' %}" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>

<body>
    <div class="container bg-light d-flex flex-column sticky-footer-wrapper min-vh-100">
        <header class="jumbotron">
            <h1 class="text-center">
                <img src="{% static '/img/logo.png' %}" class="rounded-circle" alt="logo" />
                <span class="text-nowrap">ONG Ayuda a un Peludo</span>
            </h1>
            <p class="text-justify">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquam repellat earum fuga? Nihil adipisci in
                ut labore nobis, earum eos possimus ex eum eveniet delectus suscipit mollitia perspiciatis, repellat
                vitae!
            </p>
        </header>
        <nav class="navbar navbar-expand-md bg-light">

            <a class="navbar-brand" href="/home/">
                <img src="{% static '/img/logo.png' %}" class="rounded-circle" width="80" alt="Logo" />
            </a>

            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/home/">Inicio</a>
                </li>

                <!-- Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Mascotas
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="/perros/">Perros</a>
                        <a class="dropdown-item" href="/gatos/">Gatos</a>
                    </div>
                </li>

                <li class="nav-item">

                    <a class="nav-link" href="/contacto/">Contacto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/proveedores/">Proveedores</a>
                </li>
            </ul>
        </nav>
        <h2>Agregar Proveedores</h2>
        <br>
        <form action="" method="POST" class="post-form">
            {% csrf_token %}            
            <div class="container">
                <br>                
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Rut:</label>
                    <div class="col-sm-4">
                        {{form.rut}}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Razón Social:</label>
                    <div class="col-sm-4">
                        {{form.razon_social}}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Descripción:</label>
                    <div class="col-sm-4">
                        {{form.descripcion}}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Teléfono:</label>
                    <div class="col-sm-4">
                        {{form.telefono}}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Email:</label>
                    <div class="col-sm-4">
                        {{form.email}}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Servicio:</label>
                    <div class="col-sm-4">
                        {{form.servicio}}
                    </div>
                </div>                      
                <br> <br>
                <input type="submit" class="btn btn-danger" value="Agregar" />
                <input type="reset" class="btn btn-danger" value="Limpiar" />
            </div>
        </form>
        {% if messages %}
                        {% for m in messages %}
                            <script>
                                Swal.fire({
                                    "title": "Felicitaciones",
                                    "text": "{{m}}",
                                    "icon": "success"
                                })
                            </script>                            
                        {% endfor%}
                    {% endif %}
        {{mensaje}}
        <br>
        <footer>
            <div class="row bg-dark">
                <div class="col-12 text-center text-warning">
                    Programación Web<br />
                    Instituto Profesional Duoc UC
                </div>
            </div>
        </footer>
    </div>
</body>

</html>

Testdjango/core/templates/core/contacto.html
<!DOCTYPE html>
<html lang="es">

<head>
    {% load static %}
    <title>ONG Ayuda a un peludo</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/estilo.css">
    <link href="{% static 'css/estilo_tabla.css' %}" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="container bg-light d-flex flex-column sticky-footer-wrapper min-vh-100">
        <header class="jumbotron">
            <h1 class="text-center">
                <img src="{% static '/img/logo.png' %}" class="rounded-circle" alt="logo" />
                <span class="text-nowrap">ONG Ayuda a un Peludo</span>
            </h1>
            <p class="text-justify">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquam repellat earum fuga? Nihil adipisci in
                ut labore nobis, earum eos possimus ex eum eveniet delectus suscipit mollitia perspiciatis, repellat
                vitae!
            </p>
        </header>
        <nav class="navbar navbar-expand-md bg-light">

            <a class="navbar-brand" href="#">
                <img src="{% static '/img/logo.png' %}" class="rounded-circle" width="80" alt="Logo" />
            </a>

            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/home/">Inicio</a>
                </li>

                <!-- Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Mascotas
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="/perros/">Perros</a>
                        <a class="dropdown-item" href="/gatos/">Gatos</a>
                    </div>
                </li>

                <li class="nav-item">

                    <a class="nav-link" href="/contacto/">Contacto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/proveedores/">Proveedores</a>
                </li>
            </ul>
        </nav>
        <main class="flex-fill">
            <section>
                <h2>Contacto</h2>
                <div class="form-group">
                    <form id="formulario-contacto" name="formularioContacto" action="formulario-enviado.html"
                        method="POST">

                        <div class="row">
                            <div class="col-md-12">
                                <label for="fieldTipoContacto">
                                    Tipo:<span class="alert alert-danger" role="alert"></span>
                                </label>
                                <select id="fieldTipoContacto" name="tipoContacto" class="form-control">
                                    <option value="">-- seleccione un tipo --</option>
                                    <option value="felicitaciones">Felicitaciones</option>
                                    <option value="sugerencia">Sugerencia</option>
                                    <option value="reclamo">Reclamo</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label for="fieldNombre">
                                    Nombre:<span class="alert alert-danger" role="alert"></span>
                                </label>
                                <input id="fieldNombre" class="form-control" type="text" name="nombre" />
                            </div>
                            <div class="col-md-6">
                                <label for="fieldEmail">
                                    Email:
                                    <span class="alert alert-danger" role="alert"></span>
                                </label>
                                <input id="fieldEmail" class="form-control" type="email" name="email" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label for="fieldFechaNacimiento">
                                    Fecha Nacimiento:
                                    <span class="alert alert-danger" role="alert"></span>
                                </label>
                                <input id="fieldFechaNacimiento" class="form-control" type="date"
                                    name="fecha_nacimiento" />
                            </div>
                            <div class="col-md-6">
                                <label for="fieldRut">
                                    Rut:
                                    <span class="alert alert-danger" role="alert"></span>
                                </label>
                                <input id="fieldRut" class="form-control" type="text" name="rut" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <label for="fieldComentario">
                                    Comentario:
                                    <span class="alert alert-danger" role="alert"></span>
                                </label>
                                <textarea id="fieldComentario" class="form-control" name="comentario"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 text-right">
                                <button type="submit" class="btn btn-success" name="submit">Enviar</button>
                                <button type="reset" class="btn btn-info" name="reset">Limpiar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </main>
        <footer>
            <div class="row bg-dark">
                <div class="col-12 text-center text-warning">
                    Programación Web<br />
                    Instituto Profesional Duoc UC
                </div>
            </div>
        </footer>
    </div>
</body>

</html>

Testdjango/core/templates/core/home.html
<!DOCTYPE html>
<html lang="es">

<head>
    {% load static %}
    <title>ONG Ayuda a un peludo</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/estilo.css">
    <link href="{% static 'css/estilo_tabla.css' %}" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="container bg-light d-flex flex-column sticky-footer-wrapper min-vh-100">
        <header class="jumbotron">
            <h1 class="text-center">
                <img src="{% static '/img/logo.png' %}" class="rounded-circle" alt="logo" />
                <span class="text-nowrap">ONG Ayuda a un Peludo</span>
            </h1>
            <p class="text-justify">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquam repellat earum fuga? Nihil adipisci in
                ut labore nobis, earum eos possimus ex eum eveniet delectus suscipit mollitia perspiciatis, repellat
                vitae!
            </p>
        </header>
        <nav class="navbar navbar-expand-md bg-light">

            <a class="navbar-brand" href="/home/">
                <img src="{% static '/img/logo.png' %}" class="rounded-circle" width="80" alt="Logo" />
            </a>

            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/home/">Inicio</a>
                </li>

                <!-- Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Mascotas
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="/perros/">Perros</a>
                        <a class="dropdown-item" href="/gatos/">Gatos</a>
                    </div>
                </li>

                <li class="nav-item">

                    <a class="nav-link" href="/contacto/">Contacto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/proveedores/">Proveedores</a>
                </li>
            </ul>
        </nav>
        <main class="flex-fill">
            <div class="row">
                <div class="col-12">
                    <h2>Inicio</h2>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Voluptatum error quisquam dolorum velit id, iste, hic laborum
                        laboriosam quibusdam aliquid recusandae eveniet sapiente veritatis
                        ratione ea saepe aperiam officiis rem.
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <section>
                        <h3>Integrantes</h3>
                        <ul>
                            <li>Jose Huircaman</li>
                            <li>Victor Castro</li>
                            <li>Kevin Paz</li>
                        </ul>
                    </section>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <section>
                        <h3>Mascotas</h3>
                    </section>
                </div>
            </div>
            <div class="row">
                <div class="col-6 text-center">
                    <a href="/perros/" title="Perros">
                        <img src="{% static '/img/seccion-perros.jpg' %}" title="Perros" alt="Perros"
                            class="rounded-circle img-thumbnail" width="250" />
                    </a>
                </div>
                <div class="col-6 text-center">
                    <a href="/gatos/" title="Gatos">
                        <img src="{% static '/img/seccion-gatos.jpeg' %}" title="Gatos" alt="Gatos"
                            class="rounded-circle img-thumbnail" width="250" />
                    </a>
                </div>
            </div>
        </main>
        <footer>
            <div class="row bg-dark">
                <div class="col-12 text-center text-warning">
                    Programación Web<br />
                    Instituto Profesional Duoc UC
                </div>
            </div>
        </footer>
    </div>
</body>

</html>

Testdjango/core/templates/core/proveedores.html
<!DOCTYPE html>
<html lang="es">

<head>
    {% load static %}
    <title>ONG Ayuda a un peludo</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/estilo.css">
    <link href="{% static 'css/estilo_tabla.css' %}" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


</head>

<body>
    <div class="container bg-light d-flex flex-column sticky-footer-wrapper min-vh-100">
        <header class="jumbotron">
            <h1 class="text-center">
                <img src="{% static '/img/logo.png' %}" class="rounded-circle" alt="logo" />
                <span class="text-nowrap">ONG Ayuda a un Peludo</span>
            </h1>
            <p class="text-justify">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquam repellat earum fuga? Nihil adipisci in
                ut labore nobis, earum eos possimus ex eum eveniet delectus suscipit mollitia perspiciatis, repellat
                vitae!
            </p>
        </header>
        <nav class="navbar navbar-expand-md bg-light">

            <a class="navbar-brand" href="#">
                <img src="{% static '/img/logo.png' %}" class="rounded-circle" width="80" alt="Logo" />
            </a>

            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/home/">Inicio</a>
                </li>

                <!-- Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Mascotas
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="/perros/">Perros</a>
                        <a class="dropdown-item" href="/gatos/">Gatos</a>
                    </div>
                </li>

                <li class="nav-item">

                    <a class="nav-link" href="/contacto/">Contacto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/proveedores/">Proveedores</a>
                </li>
            </ul>
        </nav>
        <main class="flex-fill">
            <div class="row">
                <div class="col-12">
                    <h2>Proveedores</h2>                    
                </div>
            </div>
            <br>
            <div class="container">
                <div class="row">
                    {{mensaje}}
                    <table>
                        <tr>
                            <th>Rut</th>
                            <th>Razon Social</th>
                            <th>Descripcion</th>
                            <th>Servicio</th>
                            <th>Operacion</th>
                        </tr>
                        {% for p in proveedores %}
                        <tr>
                            <td>{{ p.rut | title }}</td>
                            <td>{{ p.razon_social | title }}</td>
                            <td>{{ p.descripcion }}</td>
                            <td>{{ p.servicio }}</td>
                            <td>
                                <a class="btn btn-primary" href="{% url 'core:modificar' p.id  %}">Modificar</a>
                                <a class="btn btn-primary" href="{% url 'core:eliminar' p.id  %}">Eliminar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                    {% if messages %}
                    {% for m in messages %}
                    <script>
                        Swal.fire({
                            "title": "Felicitaciones",
                            "text": "{{m}}",
                            "icon": "success"
                        })
                    </script>
                    {% endfor%}
                    {% endif %}
                </div>
                <br>
                <a class="btn btn-danger float-right" href="/agregar/">
                    <b>Agregar</b>
                </a>
            </div>
        </main>
        <br>
        <footer>
            <div class="row bg-dark">
                <div class="col-12 text-center text-warning">
                    Programación Web<br />
                    Instituto Profesional Duoc UC
                </div>
            </div>
        </footer>

    </div>

</body>

</html>